---

- hosts: all
  
  tasks:
    - name: Disallow password authentication
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: Restart SSH
      become: true
      
    - name: Verify that UFW is installed
      apt:
        name: ufw
        state: present
      become: true
      register: ufw_installation
       
    - name: Allow access on SSH port
      ufw:
        port: ssh
        policy: allow
        rule: limit
        proto: tcp
      become: true
      
    - name: Configure UFW to deny access on all ports
      ufw:
        state: enabled
        policy: deny
      become: true
      when: ufw_installation.changed
      
  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
      become: true

- hosts: database
  tasks:
    - name: Verify Postgres repo key is available
      apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present
      become: true

    - name: Add postgres repo
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main"
        state: present
        update_cache: yes
      become: true

    - name: "Verify {{ item }} is installed" 
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - python-psycopg2
        - postgresql-9.5
      become: true
 
    - name: Verify existence of the f8forum_db
      postgresql_db:
        name: f8forum_db
        state: present
      become_user: postgres
      become: true
    
    - name: Revoke all permissions for the f8forum_db
      postgresql_privs:
        db: f8forum_db
        privs: ALL
        type: database
        role: PUBLIC
        state: absent
      become_user: postgres
      become: true
      
    - name: Create F8Forum database
      postgresql_db:
        name: f8forum_db
      become_user: postgres
      become: true

    - name: Create F8Forum user
      postgresql_user:
        name: f8forum_user
        password: f8forum_user
        db: f8forum_db
        priv: ALL
        role_attr_flags: NOCREATEDB,NOSUPERUSER
      become_user: postgres
      become: true

    - name: Allow access from the Java web application
      lineinfile:
        dest: /etc/postgresql/9.5/main/pg_hba.conf
        line: 'host  all  all   192.168.33.20/32   md5'
      become: true
      notify: Restart PostgreSQL service

    - name: Allow access from all addresses
      lineinfile:
        dest: /etc/postgresql/9.5/main/postgresql.conf
        line: "listen_addresses = '*'"
        insertafter: "#listen_addresses = ’localhost’"
      become: true
      notify: Restart PostgreSQL service

    - name: Allow access on the Postgres port
      ufw:
        port: 5432
        policy: allow
      become: true
    
  handlers:
    - name: Restart PostgreSQL service
      service:
        name: ssh
        state: restarted
      become: true

- hosts: web
  tasks:
    - name: Add Jessie backports repo
      apt_repository:
        repo: "deb http://ftp.de.debian.org/debian jessie-backports main"
        state: present
        update_cache: yes
      become: true

    - name: Install OpenJDK JRE 8
      apt:
        name: openjdk-8-jre
        default_release: jessie-backports
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - name: Create the F8Forum data directory
      file:
        path: /opt/f8forum
        state: directory
      become: true

    - name: Copy start script into the data directory
      copy:
        src: web/start.sh
        dest: /opt/f8forum
        mode: 0755
      become: true

    - name: Copy F8Forum Jar into the data directory
      copy:
        src: web/f8forum.jar
        dest: /opt/f8forum
        mode: 0755
      become: true

    - name: Start F8Forum application
      command: /opt/f8forum/start.sh &
      become: true
...
